//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_glaseado
    {
        public int id_producto_glaseado { get; set; }
        public Nullable<int> cantidad_glaseada { get; set; }
        public Nullable<System.DateTime> fecha_glaseada { get; set; }
        public Nullable<int> fk_id_producto_proceso { get; set; }
        public Nullable<int> fk_id_estado_glaseado { get; set; }
    
        public virtual estado_glaseado estado_glaseado { get; set; }
        public virtual producto_proceso producto_proceso { get; set; }
        public virtual producto producto { get; set; }
    }
}
