//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor_producto
    {
        public int id_producto_proveedor { get; set; }
        public Nullable<int> fk_id_producto { get; set; }
        public Nullable<int> fk_id_provvedor { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
