//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatagonesF
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_proceso
    {
        public int id_producto_proceso { get; set; }
        public int cantidad_procesada { get; set; }
        public System.DateTime fecha_proceso { get; set; }
        public int fk_id_producto { get; set; }
        public int fk_estado_producto { get; set; }
    
        public virtual estado_producto estado_producto { get; set; }
        public virtual producto producto { get; set; }
    }
}
