//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatagonesF
{
    using System;
    using System.Collections.Generic;
    
    public partial class telefono_personal
    {
        public int id_telefono_personal { get; set; }
        public Nullable<int> num1_personal { get; set; }
        public Nullable<int> num2_personal { get; set; }
        public Nullable<int> fk_rut_personal { get; set; }
    
        public virtual personal personal { get; set; }
    }
}
