//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patagones
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PatagonesEntities : DbContext
    {
        public PatagonesEntities()
            : base("name=PatagonesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<cargo_personal> cargo_personal { get; set; }
        public virtual DbSet<categoria_producto> categoria_producto { get; set; }
        public virtual DbSet<personal> personal { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<producto_glaseado> producto_glaseado { get; set; }
        public virtual DbSet<producto_proceso> producto_proceso { get; set; }
        public virtual DbSet<proveedor> proveedor { get; set; }
        public virtual DbSet<proveedor_producto> proveedor_producto { get; set; }
        public virtual DbSet<registro> registro { get; set; }
        public virtual DbSet<telefono_personal> telefono_personal { get; set; }
    }
}
