//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patagones
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor_producto
    {
        public int Id { get; set; }
        public int FkProducto { get; set; }
        public int FkProveedor { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
