//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patagones
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public registro()
        {
            this.producto1 = new HashSet<producto>();
        }
    
        public int Id { get; set; }
        public int CantidadCompra { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public string NumeroFactura { get; set; }
        public string Lote { get; set; }
        public string TipoDocumento { get; set; }
        public int FkProducto { get; set; }
        public int FkPersonal { get; set; }
    
        public virtual personal personal { get; set; }
        public virtual producto producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto> producto1 { get; set; }
    }
}
